CREATE DATABASE IF NOT EXISTS igfss;
USE igfss;

CREATE TABLE IF NOT EXISTS MEMBERS (
    fidn INTEGER NOT NULL AUTO_INCREMENT,
    memberType VARCHAR(30) NOT NULL,
    spouse1Name VARCHAR(50) NOT NULL,
    spouse2Name VARCHAR(50) NOT NULL,
    spouse1Phone VARCHAR(20) NOT NULL,
    spouse2Phone VARCHAR(20) NOT NULL,
    spouse1Email VARCHAR(80) NOT NULL UNIQUE,
    spouse2Email VARCHAR(80) NOT NULL,
    address VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    yearsMarried INTEGER,
    PRIMARY KEY (fidn)
);

ALTER TABLE MEMBERS AUTO_INCREMENT = 501;

CREATE TABLE IF NOT EXISTS CHILDREN (
    childId INTEGER NOT NULL AUTO_INCREMENT,
    fidn INTEGER NOT NULL,
    gender VARCHAR(20) NOT NULL,
    age INTEGER NOT NULL,
    PRIMARY KEY (childId),
    FOREIGN KEY (fidn) REFERENCES MEMBERS(fidn) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EVENTS (
    eventId INTEGER NOT NULL AUTO_INCREMENT,
    fidn INTEGER NOT NULL,
    eventType VARCHAR(50) NOT NULL,
    eventDate VARCHAR(30) NOT NULL,
    eventTime VARCHAR(30) NOT NULL,
    duration VARCHAR(50) NOT NULL,
    venue VARCHAR(100) NOT NULL,
    cost DOUBLE NOT NULL,
    PRIMARY KEY (eventId),
    FOREIGN KEY (fidn) REFERENCES MEMBERS(fidn) ON DELETE CASCADE
);

ALTER TABLE EVENTS AUTO_INCREMENT = 1001;
